# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FCM_Sample_Topic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Messaging'

  # Pods for FCM_Sample_Topic

end
